package edu.unifi.controller;

public enum MessageType {
    DELETE_TABLE,
    ADD_TABLE,
    UPDATE_TABLE,
    DELETE_DISH,
    ADD_DISH,
    UPDATE_DISH,
    ERROR, UPDATE_ROOM, DELETE_ROOM, ADD_ROOM, EXIT,
    ADD_ORDER, DELETE_ORDER, UPDATE_ORDER,
    CLEAN_CHECK,
    WRONG_CREDENTIALS, USER_ALREADY_EXISTS, USER_CREATED, USER_DELETED, USER_UPDATED

}
